services:
  mysql:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: aiot_data
      MYSQL_USER: "aiot"
      MYSQL_PASSWORD: "aiotpass"
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  mosquitto:
    image: eclipse-mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"

volumes:
  db_data: